model_path : /Users/treecollector/Desktop/test/model/fakecatcher/misc/face_landmarker.task
meta_data_csv_path : /root/audio-visual-forensics/data/FakeAVCeleb/balanced_sample.csv
data_root_directory:  /root/audio-visual-forensics/data
inference_data_root_directory: /root/audio-visual-forensics/data/FakeAVCeleb/balanced_sample.csv

fps_standard: 30
seg_time_interval: 3