# ROI Process
landmarker_path : /Users/treecollector/Desktop/test/model/fakecatcher/misc/face_landmarker.task

# Load Data
inference_video_path : /root/test.mp4
meta_data_csv_path : /root/audio-visual-forensics/data/FakeAVCeleb/balanced_sample.csv

# Constants
fps_standard: 30
seg_time_interval: 3

# Model
model_path: /Users/treecollector/Desktop/test/model/fakecatcher/model/fakecatcher.pth
model_type: baseCNN # baseCNN, ResNet34, EfficientNetB3, SVR, Pycaret
output_path: /Users/treecollector/Desktop/test/model/fakecatcher/output
